CREATE TABLE IF NOT EXISTS beers (
    id SERIAL PRIMARY KEY, 
    name VARCHAR(100) NOT NULL,
    brewery VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
